// Generated by CoffeeScript 1.6.3
var inotify;

inotify = function(filename, interval_time) {
  var get, time,
    _this = this;
  if (filename == null) {
    filename = "inotifypy.log";
  }
  if (interval_time == null) {
    interval_time = 5;
  }
  get = function() {
    return $.ajax({
      type: "GET",
      url: filename,
      dataType: "text",
      cache: false,
      ifModified: true
    }).done(function(data) {
      if (time < data) {
        return window.location.reload();
      } else {
        return console.log(data);
      }
    });
  };
  time = new Date().getTime() / 1000;
  return setInterval(get, interval_time * 1000);
};
