// Generated by CoffeeScript 1.6.3
var inotifypy;

inotifypy = function(interval_time, filename) {
  var get,
    _this = this;
  if (interval_time == null) {
    interval_time = 5;
  }
  if (filename == null) {
    filename = "inotifypy.log";
  }
  get = function() {
    return $.ajax({
      type: "GET",
      url: filename,
      dataType: "text",
      cache: false,
      ifModified: true
    }).done(function(data) {
      console.log(_this.time);
      if (_this.time < data) {
        return window.location.reload();
      }
    });
  };
  this.time = new Date().getTime() / 1000;
  return setInterval(get, interval_time * 1000);
};
